DROP TABLE IF EXISTS "thrall";
DROP TABLE IF EXISTS "sylvanas";

DROP TABLE IF EXISTS "joueur";

CREATE TABLE IF NOT EXISTS "thrall" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "description" TEXT,
  "img_url" TEXT
);

CREATE TABLE IF NOT EXISTS "sylvanas" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "description" TEXT,
  "img_url" TEXT
);

CREATE TABLE "joueur" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "firstname" TEXT NULL,
  "lastname" TEXT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

INSERT INTO "thrall"("id","name", "description", "img_url") VALUES
(1,'HACHE DE THRALL', 'Affuté comme jaja','https://ae01.alicdn.com/kf/S194cddc68f3a4c73ab9e7a3f398b5936v.jpg_640x640Q90.jpg_.webp'),
(2,'MARTEAU DE THRALL', 'Les chamans sont toujours un peu...marteaux','https://repliquemangacine.fr/wp-content/uploads/2023/10/2718-Replique-en-mousse-du-marteau-de-Thrall-Doomhammer-Wow.jpg'),
(3,'TOTEM DE THRALL', 'Ca fait des zoulie lumières... Et ca fait mal aussi','https://img.redbull.com/images/c_fill,g_auto,w_830,h_1186/q_auto:low,f_auto/redbullcom/2014/12/17/1331695524829_2/hearthstone-meet-the-shaman');


INSERT INTO "sylvanas"("id", "img_url") VALUES
(1,'/images/sylva.jpg');

INSERT INTO "joueur" ("id", "firstname", "lastname", "email", "password") VALUES
(1,'John', 'Doe', 'john@example.com', 'hashedpassword')
